import { FaAppleAlt, FaMobileAlt, FaTshirt } from 'react-icons/fa';
import {
    FaGem,
    FaCouch,
    FaBasketShopping,
    FaMotorcycle,
    FaShoePrints,
    FaLaptop,
    FaWatchmanMonitoring,
    FaBlender,
    FaSprayCanSparkles,
    FaTabletScreenButton,
    FaVolleyball,
    FaGlasses,
    FaCar,
    FaBagShopping,
    FaPersonDress,
    FaRing,
    FaPumpSoap,
    FaShirt,
    FaClock,
} from "react-icons/fa6";


export const categories = [
    { category: "beauty", Icon: <FaGem className="text-xl text-primary" /> },
    { category: "fragrances", Icon: <FaSprayCanSparkles className="text-xl text-primary" /> },
    { category: "furniture", Icon: <FaCouch className="text-xl text-primary" /> },
    { category: "groceries", Icon: <FaBasketShopping className="text-xl text-primary" /> },
    { category: "home-decoration", Icon: <FaAppleAlt className="text-xl text-primary" /> },
    { category: "kitchen-accessories", Icon: <FaBlender className="text-xl text-primary" /> },
    { category: "laptops", Icon: <FaLaptop className="text-xl text-primary" /> },
    { category: "mens-shirts", Icon: <FaTshirt className="text-xl text-primary" /> },
    // { category: "mens-shoes", Icon: <FaShoePrints className="text-xl text-primary" /> },
    // { category: "mens-watches", Icon: <FaWatchmanMonitoring className="text-xl text-primary" /> },
    // { category: "mobile-accessories", Icon: <FaMobileAlt className="text-xl text-primary" /> },
    // { category: "motorcycle", Icon: <FaMotorcycle className="text-xl text-primary" /> },
    // { category: "skin-care", Icon: <FaPumpSoap className="text-xl text-primary" /> },
    // { category: "smartphones", Icon: <FaMobileAlt className="text-xl text-primary" /> },
    // { category: "sports-accessories", Icon: <FaVolleyball className="text-xl text-primary" /> },
    // { category: "sunglasses", Icon: <FaGlasses className="text-xl text-primary" /> },
    // { category: "tablets", Icon: <FaTabletScreenButton className="text-xl text-primary" /> },
    // { category: "tops", Icon: <FaShirt className="text-xl text-primary" /> },
    // { category: "vehicle", Icon: <FaCar className="text-xl text-primary" /> },
    // { category: "womens-bags", Icon: <FaBagShopping className="text-xl text-primary" /> },
    // { category: "womens-dresses", Icon: <FaPersonDress className="text-xl text-primary" /> },
    // { category: "womens-jewellery", Icon: <FaRing className="text-xl text-primary" /> },
    // { category: "womens-shoes", Icon: <FaShoePrints className="text-xl text-primary" /> },
    // { category: "womens-watches", Icon: <FaClock className="text-xl text-primary" /> },
];